require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/Documentation:
  Exclude:
    - app/helpers/application_helper.rb
    - app/models/application_record.rb
    - config/application.rb
