default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails_template

development:
  <<: *default
  database: rails_template_development

test:
  <<: *default
  database: rails_template_test

production:
  <<: *default
  database: rails_template_production
  password: <%= ENV['RAILS_TEMPLATE_DATABASE_PASSWORD'] %>
